version: "3.8"

services:
  # UniFi MCP Server
  unifi-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unifi-mcp-server
    restart: unless-stopped
    environment:
      # UniFi Controller Settings
      - UNIFI_GATEWAY_IP=${UNIFI_GATEWAY_IP:-192.168.1.1}
      - UNIFI_API_KEY=${UNIFI_API_KEY}
      - UNIFI_SITE_ID=${UNIFI_SITE_ID:-default}
      - UNIFI_VERIFY_SSL=${UNIFI_VERIFY_SSL:-false}
      - UNIFI_TIMEOUT=${UNIFI_TIMEOUT:-30000}
      - UNIFI_MAX_RETRIES=${UNIFI_MAX_RETRIES:-3}

      # Server Configuration
      - SERVER_NAME=${SERVER_NAME:-UniFi Network MCP Server}
      - SERVER_VERSION=${SERVER_VERSION:-1.0.0}
      - LOG_LEVEL=${LOG_LEVEL:-info}

      # Performance Settings
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-300}
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE:-60}
      - MAX_CONCURRENT_CONNECTIONS=${MAX_CONCURRENT_CONNECTIONS:-5}

      # Node.js Settings
      - NODE_ENV=${NODE_ENV:-production}
      - TZ=${TZ:-UTC}

    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Network configuration
    networks:
      - unifi-network

    # Volumes for persistent data
    volumes:
      - unifi-logs:/app/logs
      - unifi-cache:/app/cache

  # Optional: Nginx reverse proxy (for multiple MCP servers)
  nginx:
    image: nginx:alpine
    container_name: unifi-mcp-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - unifi-mcp-server
    networks:
      - unifi-network
    profiles:
      - proxy

  # Development service with hot reload
  unifi-mcp-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: unifi-mcp-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - UNIFI_GATEWAY_IP=${UNIFI_GATEWAY_IP}
      - UNIFI_API_KEY=${UNIFI_API_KEY}
      - UNIFI_SITE_ID=${UNIFI_SITE_ID:-default}
      - UNIFI_VERIFY_SSL=false
    volumes:
      - .:/app
      - /app/node_modules
      - unifi-dev-logs:/app/logs
    networks:
      - unifi-network
    profiles:
      - development

networks:
  unifi-network:
    driver: bridge
    name: unifi-network

volumes:
  unifi-logs:
    name: unifi-logs
  unifi-cache:
    name: unifi-cache
  unifi-dev-logs:
    name: unifi-dev-logs
